### ISSUE TITLE
Modify GitHub Actions workflow

### ISSUE THREAD

**Issue by jprestop** [NCAR/wps_wrf_workflow#42]
## Describe the Task ##
On 4/21/25, NCAR public GitHub repositories received an email about changes in the GitHub organization.  We need to modify our current workflow in order to comply with these changes.

Due to “GitHub Token permissions will follow least privileged access guidelines and provide only the required permissions scope needed for the workflow.”, we should explicitly specify permissions at the workflow or job level to help ensure that even if a workflow is compromised, the potential damage is limited to only the explicitly permitted actions.
```
permissions:
  contents: read      # Only read repository contents
  actions: read       # Required for using 'actions/upload-artifact'
  pull-requests: read  # For workflows triggered by pull requests
  # Other permissions set to none by default
```

### Time Estimate ###
<1 day

### Relevant Deadlines ###
May 8, 2025

### New Parameters ###
NONE

### Technical References ###
NONE

### Funding Source ###
651020

### Assignee ###
- [x] Assign this Task to the appropriate person

### Labels ###
- [x] Select **component**
- [x] Select **priority**
- [x] Select **requestor(s)**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
